apiVersion: v1
kind: PersistentVolume
metadata:
  name: newdemovasten52
  labels:
    name: newdemovasten52
spec:
  capacity:
    storage: 1T
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  nfs:
    path: /newdemovasten52
    server: 10.219.42.202
