apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fileserver-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: standard
  volumeName: newdemovasten52
  resources:
    requests:
      storage: 1T
  selector:
     matchLabels:
       name: newdemovasten52
